### ISSUE TITLE
"project": missing name for module "index" for jfrog/project provider

### ISSUE THREAD

**Issue by mjeffryes** [pulumi/pulumi-terraform-provider#27]
Looks like some variation of failure to infer the right prefix? 

```
❯ pulumi package add terraform-provider registry.terraform.io/jfrog/project
error: failed to get schema: parameterize: rpc error: code = Unknown desc = 1 error occurred:
	* resources:
1 error occurred:
	* "project": missing name for module "index"
```

**Comment by iwahbe** [comment]
Not quite. The provider has a resource called [`project`](https://registry.terraform.io/providers/jfrog/project/latest/docs/resources/project). The mapper assumes that each TF resource token is of the form `<prefix>_<module? + name>`. It doesn't handle `<prefix>` correctly.
