### ISSUE TITLE
Allow recording gRPC logs between the Pulumi and TF providers

### ISSUE THREAD

**Issue by iwahbe** [pulumi/pulumi-terraform-provider#37]
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

This would help us debug provider bugs when we are unable to reproduce the problem locally (say for lack of credentials or access to the underlying provider).

Users should be able to set a variable like:

```console
$ PULUMI_DEBUG_TF_LOGS=tf_logs.json pulumi up
```

This would work similarly to `PULUMI_DEBUG_LOGS=logs.json`. If we had the TF schema, the Pulumi logs and TF logs, we could then correlate commands (Pulumi create -> TF create).

**Comment by t0yv0** [comment]
It could be quite useful to emulate this for normal bridge even when not speaking TF protocol quite as yet.
