### ISSUE TITLE
Update docs for YAML support

### ISSUE THREAD

**Issue by polarathene** [pulumi/pulumi-terraform-provider#41]
> https://www.pulumi.com/registry/packages/terraform-provider/
> 
> ![Image](https://github.com/user-attachments/assets/358a2ff3-c8fe-4772-b06e-5a2ed111c6a0)

The referenced July 2024 issue has [since been resolved](https://github.com/pulumi/pulumi-yaml/issues/626#issuecomment-2402825387) in Oct 2024: https://github.com/pulumi/pulumi-yaml/pull/616#issuecomment-2402825325

---

https://github.com/pulumi/pulumi-terraform-provider/blob/46abc094151e7159d0222bfd5af7a76287f99e79/docs/_index.md?plain=1#L134-L144

https://github.com/pulumi/pulumi-terraform-provider/blob/46abc094151e7159d0222bfd5af7a76287f99e79/docs/_index.md?plain=1#L223-L229

**Comment by VenelinMartinov** [comment]
Hey, thanks for pointing this out. I've raised a PR to add instructions for YAML.

**Comment by polarathene** [comment]
Thanks for the quick resolution! I left a comment on the PR as someone who's not experienced with Pulumi or TF.

Looks like the docs rely on new release to be built, so I guess that won't go live until something new warrants publishing another release?

**Comment by VenelinMartinov** [comment]
Yeah, the docs only update on release, I'll push one out so we can get this fixed.
