### ISSUE TITLE
Missing parameter on instaclustr_kafka_cluster_v2 resource

### ISSUE THREAD

**Issue by mjeffryes** [pulumi/pulumi-terraform-provider#8]
### What happened?

(from slack: https://pulumi.slack.com/archives/C07A45FT70W/p1722618420220089) 
I bridged a more complex provider and I have a possible issue I wanted to bring up.  The provider is fairly large/complex, and the code generation ran fine.  However I seem to be missing a property for a nested object.

There is an output property data_centres on the generated KafkaClusterV2 object, but I don't see any way of setting the data_centres property in KafkaClusterV2Args.

### Example

The TF code would look like:

```
resource "instaclustr_kafka_cluster_v2" "example" {
  auto_create_topics = true
  client_to_cluster_encryption = true
  pci_compliance_mode = false
  data_centre {
    cloud_provider = "AWS_VPC"
    name = "AWS_VPC_US_EAST_1"
    network = "10.0.0.0/16"
    node_size = "KFK-PRD-r6g.large-250"
    number_of_nodes = 3
    region = "US_EAST_1"
  }
 
  dedicated_zookeeper {
    zookeeper_node_count = 3
    zookeeper_node_size = "KDZ-PRD-m6g.large-80"
  }
 
  default_replication_factor = 3
  private_network_cluster = false
  kafka_version = "[x.y.z]"
  default_number_of_partitions = 3
  name = "MyKafkaCluster"
  sla_tier = "NON_PRODUCTION"
  allow_delete_topics = true
}
```

### Output of `pulumi about`

pulumi version 3.126.0

### Additional context

Generated python file: https://pulumi.slack.com/files/U064QRA1BPT/F07FZ6K2CD6/kafka_cluster_v2.py?origin_team=T4PBPMA8J&origin_channel=CK21FUGUA

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by t0yv0** [comment]
Assuming this is the instaclustr provider I'm having some difficulty reproing this:

```
pulumi package add terraform-provider instaclustr/instaclustr 
error: failed to get schema: parameterize: rpc error: code = Unknown desc = provider registry registry.opentofu.org does not have a provider named registry.opentofu.org/instaclustr/instaclustr
```

IF there are any more pointers on how the provider was bridged those are highly appreciated.

For now I will try to build the instaclustr provider locally and see if I can extract the schema the dynamic way and repro indirectly.

**Comment by t0yv0** [comment]
```
James Connell
  2 minutes ago
pulumi package gen-sdk terraform-provider --language python --out instaclustr -- [registry.terraform.io/instaclustr/instaclustr](http://registry.terraform.io/instaclustr/instaclustr)
or in your case pulumi package add terraform-provider  [registry.terraform.io/instaclustr/instaclustr](http://registry.terraform.io/instaclustr/instaclustr)
```

The above worked, investigating.
